Update gameplay guide
UnvanquishedAssets/unvanquished_src.dpkdir pull request #110
Opened 2022-05-29 12:31 UTC by necessarily-equal

2022-05-29 22:22 UTC, illwieckz commented on ui/help_gameplay.rml
> +				Feel free to take join us in the community and developer chats!<br />
> Feel free to ~~take~~ join us

?

2022-05-29 22:40 UTC, necessarily-equal commented on ui/help_gameplay.rml
> +				Feel free to take join us in the community and developer chats!<br />
Oh right, fixed

2022-06-04 12:01 UTC, bmorel commented
Except for the comment I left: LGTM.
As for @slipher 's comment, I think the removed text was indeed completely obsolete and thus removing it is fine.

2022-06-04 12:02 UTC, bmorel requested changes

2022-06-05 06:21 UTC, slipher commented on ui/help_gameplay.rml
> +				Staying at an intermediate distance of the
There are 3 healing mechanics based on alien structures. Booster: 8x/range 200, any building: 4x/`creepSize` (range depends on building), and overmind/eggs: 2x/700.

2022-06-05 08:38 UTC, bmorel commented on ui/help_gameplay.rml
> +				Staying at an intermediate distance of the
Yes, right. I thought the 2x one was given by any building, and did experiments yesterday on that. The distance is so far away, and the heal boost so small though, than it seems barely useful to me (that's a different problem).
I still find this phrase confusing, and since it comes after the § on the healing (and poison got in the middle of this), I fear that people might consider it's a high heal rate.
At least make it explicit that this regen boost is smaller than when one is walking on creep?

2022-06-05 17:55 UTC, slipher commented on ui/help_gameplay.rml
> -				reactor now supplies power to every place on the map, but
#112 adds text explaining this elsewhere so it's OK to delete. LGTM

2022-06-05 18:13 UTC, necessarily-equal commented on ui/help_gameplay.rml
> +				Staying at an intermediate distance of the
I've added a commit which hopefully makes this more clear. It also explains the other aspects of alien healing that weren't mentioned yet.

My unvanquished build is broken at the moment though, so I can't test that this text didn't overflow or anything, so hopefully it is fine.

2022-06-05 20:05 UTC, bmorel approved these changes

2022-06-05 20:05 UTC, bmorel commented
LGTM

2022-06-05 20:06 UTC, merged