add a possible position indicator under speedometer
UnvanquishedAssets/unvanquished_src.dpkdir pull request #144
Opened 2022-08-02 15:13 UTC by bmorel

This will only show if speedometer is enabled, not sure how to prevent than problem while keeping things reasonably simple. I'm open to suggestions.

2022-08-02 17:18 UTC, necessarily-equal requested changes

2022-08-02 17:18 UTC, necessarily-equal commented on ui/hud_basics.rml
> +		}
I see that this was copy-pasted, how about joining the rules with a "," (e.g. `speedometer, position_indicator {}` and `speedometer span, position_indicator span {}`).

2022-08-02 17:18 UTC, necessarily-equal commented on ui/hud_basics.rml
>  	</if>
Here I would swap the `region` and the `if`, this way you can use a second if on the second one

2022-08-04 08:56 UTC, bmorel commented on ui/hud_basics.rml
> +		}
Yes, it was. I know (almost) nothing about CSS so I just go the quick'n dirty way. There might be much cleaner ways to do it.
But, this works, and is pretty useful, as it avoid doing a bind to emit a `/where` command. Examples of use cases are for players to report bugs in a more accurate way than doing a screen shot, or knowing where bots suicide exactly (which requires having bots saying where they suicide, which is a feature that was refused but that I keep on my instances as it can help players identify problems in their base).

2022-08-06 12:40 UTC, bmorel commented on ui/hud_basics.rml
>  	</if>
This makes the code buggy.

2022-08-06 12:44 UTC, bmorel commented on ui/hud_basics.rml
> +		}
About the copy-pasting, I'd be ok to not do that, if the code was clean. Otherwise, there's no way I can write clean stuff in that area, since I do not know CSS "subtleties" (to be polite).
One of the requested changes looks like a codestyle nitpick, and the other one makes the code buggy.

2022-08-06 12:44 UTC, bmorel commented
One of the requested changes looks like a codestyle nitpick, and the other one makes the code buggy.

2022-08-18 22:35 UTC, necessarily-equal commented on ui/hud_basics.rml
> +		speedometer,position_indicator span
This is missing the span:

```suggestion
		speedometer span,
		position_indicator span
```

2022-08-18 22:38 UTC, bmorel commented on ui/hud_basics.rml
> +		speedometer,position_indicator span
what's the point? I thought initial comment was to reduce duplication, and solution I did works according to tests.

2022-08-23 19:53 UTC, necessarily-equal commented on ui/hud_basics.rml
> +		speedometer,position_indicator span
The two have a different meaning. `speedometer span` means the `span` inside the speedometer, and `position_indicator` without the span just means the span. While you probably wanted to match the `span`.

To make this more abvious, and to avoid long lines, I slightly prefer to put it on separate lines like I suggested:

```css
speedometer span,
position_indicator span
```

2022-08-28 19:57 UTC, necessarily-equal approved these changes

2022-08-28 19:58 UTC, necessarily-equal commented
Woooo

2022-08-28 19:59 UTC, merged