split default behavior tree into species specific files
UnvanquishedAssets/unvanquished_src.dpkdir pull request #39
Opened 2021-03-11 18:30 UTC by bmorel

the splits makes it easier to understand either aliens or humans behavior, in the hope to improve them.
It also revealed some refactoring which result in less nodes, by merging e.g.

```
sequence
{
  condition test1
  condition test2
  action do_something
}
```

into:

```
condition test1 && test2
{
  action do_something
}
```

Which should be more obvious to most people.

2021-03-11 19:14 UTC, illwieckz commented
Oh yes that's clearly more readable that way! And allow to properly focus on a team for implementing improvements (less mental load). :smiley:

2021-03-11 19:41 UTC, necessarily-equal requested changes
I like how it's not even longer

2021-03-11 19:41 UTC, necessarily-equal commented on bots/default.bt
> +		behavior aliens
maybe better name the behaviours `defaultAlien` and `defaultHuman`.

2021-03-13 22:54 UTC, slipher reviewed
Overall this is a good simplification.

2021-03-13 22:54 UTC, slipher commented on bots/default.bt
> +		behavior aliens
+1

2021-03-13 22:54 UTC, slipher commented on bots/humans.bt
> +			sequence
This part changed compared to the old version

2021-03-13 23:06 UTC, bmorel commented on bots/humans.bt
> +			sequence
please tell me more? Or better, show me how I accidentally changed behavior?

2021-03-13 23:42 UTC, slipher commented on bots/humans.bt
> +			sequence
changed selector to sequence and deleted `condition haveWeapon( WP_HBUILD )`

2021-03-19 11:35 UTC, bmorel commented on bots/humans.bt
> +			sequence
Exact.
Previous behavior was: "if I do not have ckit, buy one, ELSE repair" where current code says "if I do not have ckit, buy one. repair anyway."
Do you see any reason to keep old algorithm? Or maybe I misunderstand it?

2021-03-19 23:49 UTC, slipher commented on bots/humans.bt
> +			sequence
It is not the same since the bot may decide to do something else instead of repairing, after buying the ckit.

I don't know if the changed version is better or worse, but I thought the point of this commit is to do a non-behavior-changing refactor.

2021-03-19 23:54 UTC, bmorel commented on bots/humans.bt
> +			sequence
> but I thought the point of this commit is to do a non-behavior-changing refactor.

True it was, but I feel like it was a bug: why would a bot take a ckit if not to repair? They do not know how to build (yet) and ckit can only be used to do one or the other.

2021-03-20 00:00 UTC, necessarily-equal commented
If you want to introduce unrelated changes, they belong in another 
commit IMO. Otherwise that's fine

On Fr, Mär 19, 2021 at 16:54, Morel Bérenger 
***@***.***> wrote:
> @bmorel commented on this pull request.
> 
> In bots/humans.bt:
> 
> > +			}
> +
> +			action fight
> +		}
> +	}
> +
> +	condition !haveUpgrade( UP_MEDKIT ) && healScore <= 0.25
> +	{
> +		action heal
> +	}
> +
> +	condition !teamateHasWeapon( WP_HBUILD ) && buildingIsDamaged
> +	{
> +		decorator timer( 50000 )
> +		{
> +			sequence
>> but I thought the point of this commit is to do a 
>> non-behavior-changing refactor.
>> 
> True it was, but I feel like it was a bug: why would a bot take a 
> ckit if not to repair? They do not know how to build (yet) and ckit 
> can only be used to do one or the other.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

2021-03-20 00:04 UTC, slipher commented on bots/humans.bt
> +			sequence
One possibility is that if after the bot buys a ckit, if it sees an enemy and someone else already has a ckit, it will change plans to buy a gun and try to attack the enemy.

2021-03-20 00:14 UTC, bmorel commented on bots/humans.bt
> +			sequence
I'm not really convinced, but it's not really important anyway, I'll restore previous behavior.

2021-03-20 03:15 UTC, slipher commented
End result look OK, just waiting for a rebase (so files aren't renamed multiple times etc.)

Personally I would much rather see the rebases done right away instead of delayed as late as possible. I usually look at the individual commits (isn't that what they're there for?) rather than the overall diff, so it's annoying if commits with mistakes that have already been pointed out stay in.

2021-03-20 08:35 UTC, bmorel commented
> I usually look at the individual commits (isn't that what they're there for?)

Indeed, I also consider commits a may better source of information than a simple diff (and I don't like the empty commits introduced by github when merging, neither, because they just don't make sense since other commits of the merge can be interleaved with commits of other merges). But I find it easier to address first all issues and *then* rebase to have meaningful commits (less rebases less bugs introduced while moving things before and after and fixing the resulting conflicts).
The 3 commits here (should be only 3, one should not have been here... sigh) can easily be squashed thought.

2021-04-03 23:22 UTC, merged

2021-07-20 01:44 UTC, slipher commented
The [problem](https://github.com/Unvanquished/Unvanquished/issues/1374) may have been that
```
sequence
{
  condition test1
  action do_something
}
```
and
```
condition test1 
{
  action do_something
}
```

are NOT equivalent when `do_something` is a long-running action. The former evaluates the condition only once, while the latter evaluates it every frame.

2021-07-20 01:51 UTC, bmorel commented
I don't remember, honestly. I only know that I have a working solution since months. You can see a part of it here: https://github.com/bmorel/unvanquished_src.dpkdir/commit/7dd908000c5880b09ec8c674c40af931e9dd051e (more recent commits are not available, github is not really sexy, always requiring me to get mail and write back a stupid code...)

2021-07-20 02:03 UTC, illwieckz commented
> (more recent commits are not available, github is not really sexy, always requiring me to get mail and write back a stupid code...)

Hmm, do you know that you can [add a SSH public key](https://github.com/settings/keys) to GitHub, then use `git@github.com:bmorel/unvanquished_src.dpkdir.git` remote url? Or do I am missing something?

2021-07-20 02:06 UTC, bmorel commented
I know that, I just mostly sync stuff when I need to do a PR